create table if not exists users (
  id BIGINT generated by default as identity primary key,
  name VARCHAR(255) not null,
  email VARCHAR(512) not null,
  constraint uq_users_email unique (email)
);

create table if not exists items (
  id BIGINT generated by default as identity primary key,
  name VARCHAR(255) not null,
  description VARCHAR(512),
  is_available BOOLEAN,
  owner_id BIGINT not null references users(id)
);

create table if not exists bookings (
  id BIGINT generated by default as identity primary key,
  start_date TIMESTAMP without TIME zone not null,
  end_date TIMESTAMP without TIME zone not null,
  item_id BIGINT not null references items(id),
  booker_id BIGINT not null references users(id),
  status VARCHAR(50) not null
);

create table if not exists comments (
  id BIGINT generated by default as identity primary key,
  text VARCHAR(512) not null,
  item_id BIGINT not null references items(id),
  author_id BIGINT not null references users(id),
  created TIMESTAMP without TIME zone not null
);
